### PR TITLE
bring back silently removed to_h on secret

### PR DESCRIPTION
**Pull request by grosser**
... this used to work on 0.4 ... but then broken when upgrading to 0.5 :(

@sethvargo

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @grosser 

Thank you for the PR. This did indeed "break", but it was never an intended public API; this was just a side-effect of having inherited from Struct. Could you explain your use case a bit more? Why do you want to serialize the response into a hash?

**Comment by grosser** [comment]
We have multiple backends for our secret storage and want them to all produce a hash that we then dump in the UI https://github.com/zendesk/samson/blob/master/app/views/admin/secrets/edit.html.erb#L77-L93

**Comment by sethvargo** [comment]
Fixed in master

**Comment by grosser** [comment]
can you add the tests for field / fields too ... not important, but I thought it would be nice to test the basics ...

**Pull request closed without merging**
