### PR TITLE
Fix redirection on POST/PUT requests by not parsing the response location twice

### LINKED ISSUE #39: InvalidURIError on redirection due to double URI.parse
When a redirection happens this gem URI.parses the location and retries.

See: https://github.com/hashicorp/vault-ruby/blob/d515e7203ca1f38bcc5faffbbe8e4f0542bb2604/lib/vault/client.rb#L217

This means a URI object is passed as the path parameter in the build_uri method which results in the following exception: 

```
Exception: URI::InvalidURIError: bad URI(is not URI?): https://10.0.2.10:8200/v1/provider/tst/service/pay
--
 0: /usr/local/lib/ruby/2.2.0/uri/rfc3986_parser.rb:17:in `rescue in split'
 1: /usr/local/lib/ruby/2.2.0/uri/rfc3986_parser.rb:14:in `split'
 2: /usr/local/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
 3: /usr/local/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
 4: /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:253:in `build_uri'
 5: /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:123:in `request'
 6: /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:218:in `block in request'
 7: /usr/local/lib/ruby/2.2.0/net/http.rb:853:in `start'
 8: /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:212:in `request'
 9: /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:87:in `put'
10: /usr/local/bundle/gems/vault-0.1.5/lib/vault/api/logical.rb:47:in `write'
```

When I remove the URI.parse call from the redirection handling code at https://github.com/hashicorp/vault-ruby/blob/d515e7203ca1f38bcc5faffbbe8e4f0542bb2604/lib/vault/client.rb#L217 it works as expected

### PR DESCRIPTION
**Pull request by jurriaan**
Fixes #39

### CODE REVIEW

**Comment by JeanMertz** [comment]
:+1:

**Comment by sethvargo** [comment]
Nice! Thanks!

**Comment by sethvargo** [comment]
@jurriaan also - I'm currently in the Netherlands (Amsterdam) at a conference. If you're near Amsterdam, let me know and I'll buy you a drink :smile:

**Comment by sethvargo** [comment]
@JeanMertz too^

**Comment by jurriaan** [comment]
@serhvargo Ha, thanks! Would've liked to, but unfortunately, I'm not going to be near Amsterdam in the coming days. (as we're busy with the German launch of Blendle)

**Pull request merged**
