### PR TITLE
AWS IAM Route Support

### PR DESCRIPTION
**Pull request by computeracer**
Adds option to put in custom route to support different mount points.

### CODE REVIEW

**Comment by universam1** [comment]
Great job, this is really missing. 
+1 to get that in

**Comment by mflococodev** [comment]
Would be really useful. Thanks for adding

**Comment by computeracer** [comment]
@evanphx Saw you did some of the PRs in the past. Would you be able to do this one?

Thanks,

Dan

**Comment by computeracer** [comment]
@jefferai or @evanphx Any thoughts on this one?

Thank you for your time.

**Pull request merged**
